# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: |
        ./gradlew clean build
        ./gradlew assemble
        mkdir release
        mv build/libs/*.jar release/
        cd release
        zip -r cred-notifications.zip .
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    # Cache the dist folder for the deploy job
    - save_cache:
        key: v1-zip-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - release/cred-notifications.zip
    # run tests!
    - run: ./gradlew test
  deploy:
    docker:
    - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
    # Restore cache from the build job which contains the
    # dist folder that needs to be deployed
    - restore_cache:
        key: v1-zip-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
    #TODO create custom Docker image with Node and Yarn Installed
    # Install Node for JH Build
#    - run:
#        name: Download Node
#        command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
#    - run:
#        name: Install Node
#        command: sudo apt-get install -y nodejs
#    - run:
#        name: update-npm
#        command: sudo npm install -g npm@latest
#    - run:
#        name: Install aws-code-deploy
#        command: sudo npm install aws-code-deploy -g
    - run:
        name: Install awscli
        command: sudo pip install awscli
    - run:
        name: Deploy to S3
        command: |
          echo `pwd`
          echo `ls`
          echo `ls release`
          aws s3 cp ${CIRCLE_WORKING_DIRECTORY}/release/cred-notifications.zip s3://elasticbeanstalk-us-west-2-724072406552/releases/notification-service/cred-notifications-1.zip --region "us-west-2"
#    - run:
#          name: Run aws-code-deploy
#          command: aws-code-deploy
#          environment :
#            DEPLOY_DIR: $HOME/deploy
#
#           # We are defining the $AWS_CODE_DEPLOY_KEY and $AWS_CODE_DEPLOY_SECRET in the CircleCI Project Settings >
#           # AWS Permissions which automatically configure these for use via aws cli and are automatically read
#           # via aws-code-deploy.sh. Alternatively, these could be specified securely (not via project code) using
#           # the CircleCI Environment Variables CircleCI control panel.
#            AWS_CODE_DEPLOY_REGION: us-west-2
#            AWS_CODE_DEPLOY_APPLICATION_NAME: "CredNotification"
#            #AWS_CODE_DEPLOY_DEPLOYMENT_CONFIG_NAME: CodeDeployDefault.AllAtOnce
#            AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: "www.my-company.com"
#            #AWS_CODE_DEPLOY_SERVICE_ROLE_ARN: "arn:aws:iam::XXXXXXXXXXXXX:role/my-company-codedeploy"
#            #AWS_CODE_DEPLOY_EC2_TAG_FILTERS: "Key=Type,Value=www,Type=KEY_AND_VALUE"
#            #AWS_CODE_DEPLOY_APP_SOURCE: $HOME/deploy
#            AWS_CODE_DEPLOY_S3_FILENAME: "cred-notifications-${CIRCLE_BUILD_NUM}#${CIRCLE_SHA1:0:7}.zip"
#            AWS_CODE_DEPLOY_S3_BUCKET: elasticbeanstalk-us-west-2-724072406552/releases
#            AWS_CODE_DEPLOY_S3_KEY_PREFIX: /notification-service
#            AWS_CODE_DEPLOY_S3_LIMIT_BUCKET_FILES: 10
#            AWS_CODE_DEPLOY_S3_SSE: true
#            AWS_CODE_DEPLOY_REVISION_DESCRIPTION: "${CIRCLE_BRANCH} (#${CIRCLE_SHA1:0:7})"
#            AWS_CODE_DEPLOY_DEPLOYMENT_DESCRIPTION: "Deployed via CircleCI on $(date)"

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master



